name: .NET Core Desktop

on:
  push:
    branches: [ "MasterMainBranch" ]
  pull_request:
    branches: [ "MasterMainBranch" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

        env:
      Solution_Name: CyberChat/CyberChat.sln                     
      Configuration: ${{ matrix.configuration }}


    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

        # Remove the Setup MSBuild step completely, then use these:

    - name: Restore the application
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CyberChat-Build-${{ matrix.configuration }}
        path: |
          **/bin/${{ matrix.configuration }}/
